spring:
  application:
    name: discover-eureka-ha
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true