spring:
  application:
    name: spring-cloud-pyg-admin-merchant-client
server:
  port: 8610
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true