spring:
  application:
    name: spring-cloud-pyg-goods-service
  jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: 151866
    url: jdbc:mysql://localhost:3306/pyg?characterEncoding=utf-8
server:
  port:  8520
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
